只打印或显示numpy数组rand_arr的小数点后3位。

In [4]:
import numpy as np
rand_arr = np.random.random([5, 3])
np.set_printoptions(precision=3)
print(rand_arr)

[[0.18  0.917 0.546]
 [0.176 0.434 0.103]
 [0.843 0.246 0.738]
 [0.545 0.349 0.543]
 [0.915 0.782 0.116]]


将numpy数组a中打印的项数限制为最多6个元素。

In [9]:
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


打印完整的numpy数组a而不中断。

In [10]:
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
