如何在二维numpy数组的每一行中找到最大值？

In [2]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1, 10, [5, 3])

b = np.amax(a, axis=1)
print(a)
print(b)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
