1. 导入鸢尾属植物数据集，保持文本不变。

In [2]:
import numpy as np

file='.\iris.data'
iris=np.genfromtxt(file,delimiter=',', dtype=(float,float,float,float,object), names=True)
iris['species']=iris['species'].astype(str)
# numpy的数组元素应该都是同一类型的。类型不同的数组，dtype应为object。需要用哪一列，取出来再类型转换。
# 结构化数组 https://www.numpy.org.cn/user/basics/rec.html#%E4%BB%8B%E7%BB%8D
# np.loadtxt and np.genfromtxt operate in byte mode, which is the default string type in Python 2. But Python 3 uses unicode, and marks bytestrings with this b.
# https://stackoverflow.com/questions/33655641/b-character-added-when-using-numpy-loadtxt

In [2]:
print(iris.dtype)
print(type(iris[0]))
iris

[('sepallength', '<f8'), ('sepalwidth', '<f8'), ('petallength', '<f8'), ('petalwidth', '<f8'), ('species', 'O')]
<class 'numpy.void'>


array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

2. 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

In [3]:
sepallength=iris['sepallength'] # 内存地址相同
# sepallength=iris[].astype(np.float)
# sepalLength = np.loadtxt(outfile, dtype=float, delimiter=',', skiprows=1, usecols=[0])
print(sepallength)
print(np.mean(sepallength))
print(np.median(sepallength))
print(np.std(sepallength))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
5.843333333333334
5.8
0.8253012917851409


3. 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）。

In [4]:
smax=np.max(sepallength)
smin=np.min(sepallength)
standard=(sepallength-smin)/(smax-smin)
print(standard)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

4. 找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

In [5]:
print(np.percentile(sepallength,[5,95]))

[4.6   7.255]


5. 把iris_data数据集中的20个随机位置修改为np.nan值。

In [6]:
name=iris.dtype.names
x=np.random.randint(iris.size,size=20)
y=np.random.randint(4,size=20)
for i in range(20):
    iris[name[y[i]]][x[i]]=np.nan

In [7]:
iris

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (nan, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (nan, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, nan, 1. , nan, 'Iri

6. 在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

In [8]:
print(np.where(np.isnan(sepallength)))
print(len(np.where(np.isnan(sepallength))[0]))

(array([  5,   6,  52,  57,  59, 121, 138, 145], dtype=int64),)
8


7. 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

In [9]:
sepallength=iris['sepallength']
petallength=iris['petallength']
index=np.where(np.logical_and(sepallength<5.0, petallength>1.5))
print(index)
iris[index]

(array([ 11,  24,  29,  30, 106], dtype=int64),)


array([(4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (4.9, 2.5, 4.5, 1.7, 'Iris-virginica')],
      dtype=[('sepallength', '<f8'), ('sepalwidth', '<f8'), ('petallength', '<f8'), ('petalwidth', '<f8'), ('species', 'O')])

8. 选择没有任何 nan 值的 iris_data行。

In [10]:
index=np.where(~np.isnan(sepallength))
type(iris[name[4]][1])
for i in range(1,4):
    index=np.intersect1d(index,np.where(~np.isnan(iris[name[i]])))
iris[index]

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, 'Iris-setosa'),
       (5. , 3. , 1.6, 0.2, 'Iris-setosa'),
       (5.2, 3.5, 1.5, 0.2, 'Iri

9. 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

In [14]:
print(np.cov(sepallength[index], petallength[index]))

[[0.69031356 1.27997769]
 [1.27997769 3.11959248]]


10. 找出iris_data是否有任何缺失值。

In [58]:
outfile = r'.\iris.data'
iris_data = np.loadtxt(outfile, dtype=float, delimiter=',', skiprows=1, usecols=[0, 1, 2, 3])
i, j = iris_data.shape
np.random.seed(20201128)
iris_data[np.random.randint(i, size=20), np.random.randint(j, size=20)] = np.nan
x = np.isnan(iris_data)
print(np.any(x))

11. 在numpy数组中将所有出现的nan替换为0。

In [ ]:
iris_data[np.isnan(iris_data)]=0
iris_data

12. 找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

In [62]:
species=iris['species']
np.unique(species,return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([50, 50, 50], dtype=int64))

13. 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 --> 'small'；3-5 --> 'medium'；'>=5 --> 'large'。

In [6]:
outfile = r'.\iris.data'
petallength=np.loadtxt(outfile, dtype=float, delimiter=',', skiprows=1, usecols=2)
np.sum(np.isnan(petallength))
np.min(petallength)

1.0

In [9]:
bins = np.array([0, 3.0, 5.0, 10.0])
inds = np.digitize(petallength, bins)
label_map={1:'small', 2:'medium', 3:'large'}
petal_length_cat =[label_map[x] for x in inds]
petal_length_cat

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

14. 在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3。

In [10]:
outfile = r'.\iris.data'
iris_data = np.loadtxt(outfile, dtype=object, delimiter=',', skiprows=1)
sepalLength = iris_data[:, 0].astype(float)
petalLength = iris_data[:, 2].astype(float)
volume = (np.pi * petalLength * sepalLength ** 2) / 3
volume = volume[:, np.newaxis]
iris_data = np.concatenate([iris_data, volume], axis=1)
print(iris_data[0:10])

[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa' 38.13265162927291]
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa' 35.200498485922445]
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa' 30.0723720777127]
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa' 33.238050274980004]
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa' 36.65191429188092]
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa' 51.911677007917746]
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa' 31.022180256648003]
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa' 39.269908169872416]
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa' 28.38324242763259]
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa' 37.714819806345474]]


15. 随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。